import { useCallback, useEffect, useMemo, useState } from "react";
import { clearToken, fetchChats, fetchMeta, fetchProfile, hasToken, login } from "./api";
import { Chart } from "./components/Chart";
import { useDashboardCache } from "./hooks/useDashboardCache";
import { useI18n, type Locale, type TranslationKey, formatDate, formatNumber } from "./i18n";
import type { Chat, Dashboard, Meta, Profile, User } from "./types";

type Section = "overview" | "activity" | "chats" | "plans" | "profile";
type Period = 1 | 7 | 30 | 90;
type Metric = "messages" | "active_users" | "joins" | "moderation_actions";
const periods: Period[] = [1, 7, 30, 90];
const metrics: Metric[] = ["messages", "active_users", "joins", "moderation_actions"];

function useTheme(): ["light" | "dark", () => void] {
  const [theme, setTheme] = useState<"light" | "dark">(() => {
    const stored = localStorage.getItem("tg-manager-theme");
    return stored === "dark" ? "dark" : "light";
  });
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("tg-manager-theme", theme); }, [theme]);
  return [theme, () => setTheme((value) => value === "light" ? "dark" : "light")];
}

function initials(name: string): string { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "TG"; }
function delta(value: number | null | undefined): string { return value == null ? "new" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }

function LanguageToggle({ locale, setLocale, label = "Language" }: { locale: Locale; setLocale: (next: Locale) => void; label?: string }): React.JSX.Element {
  return <div className="language-toggle" role="group" aria-label={label}><button type="button" className={locale === "ru" ? "selected" : ""} onClick={() => setLocale("ru")}>RU</button><button type="button" className={locale === "en" ? "selected" : ""} onClick={() => setLocale("en")}>EN</button></div>;
}

function BrandMark(): React.JSX.Element { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /></span>; }

function LoginScreen({ error, onLogin }: { error: string | null; onLogin: (value: string) => void }): React.JSX.Element {
  const { locale, setLocale, t } = useI18n();
  const [theme, toggleTheme] = useTheme();
  const [value, setValue] = useState("");
  return <main className="login-page"><div className="login-top"><BrandMark /><div><LanguageToggle locale={locale} setLocale={setLocale} label={locale === "ru" ? "Язык" : "Language"} /><button className="icon-button" type="button" onClick={toggleTheme} aria-label={theme === "light" ? t("theme.dark") : t("theme.light")}>{theme === "light" ? "◐" : "○"}</button></div></div><p className="eyebrow">TELEGRAM MANAGER / ACCOUNT</p><h1>{t("login.title")}</h1><p className="login-copy">{t("login.subtitle")}</p><form onSubmit={(event) => { event.preventDefault(); if (value.trim()) onLogin(value.trim()); }}><label>{t("login.tokenLabel")}<input autoFocus value={value} onChange={(event) => setValue(event.target.value)} placeholder={t("login.tokenPlaceholder")} /></label><button className="primary" type="submit" disabled={!value.trim()}>{t("login.submit")} <span>↗</span></button></form>{error && <p className="form-error" role="alert">{error}</p>}<p className="login-note">{locale === "ru" ? "Ключ одноразовый и не сохраняется в URL или постоянном хранилище." : "The key is single-use and is never kept in the URL or durable storage."}</p></main>;
}

function Sidebar({ section, setSection, profile, theme, toggleTheme, logout, t }: { section: Section; setSection: (value: Section) => void; profile: Profile; theme: "light" | "dark"; toggleTheme: () => void; logout: () => void; t: (key: any, values?: Record<string, string | number>) => string }): React.JSX.Element {
  const items: [Section, string, string][] = [["overview", "nav.overview", "01"], ["activity", "nav.activity", "02"], ["chats", "nav.chats", "03"], ["plans", "nav.plans", "04"], ["profile", "nav.profile", "05"]];
  return <aside className="sidebar"><div className="brand"><BrandMark /><span>tg / manager</span></div><nav aria-label="Primary">{items.map(([key, label, number]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}><small>{number}</small>{t(label)}</button>)}</nav><div className="side-bottom"><button className="theme-button" onClick={toggleTheme}>{theme === "light" ? "◐" : "○"}<span>{t(theme === "light" ? "theme.dark" : "theme.light")}</span></button><button className="account-mini" onClick={() => setSection("profile")}><span className="avatar small">{initials(profile.display_name)}</span><span><b>{profile.display_name}</b><small>{profile.user.username ? `@${profile.user.username}` : "Telegram"}</small></span><span>↗</span></button><button className="logout" onClick={logout}>{t("common.logout")}</button></div></aside>;
}

function Header({ section, profile, selectedChat, chats, setSelectedChat, theme, toggleTheme, locale, setLocale, t }: { section: Section; profile: Profile; selectedChat?: number; chats: Chat[]; setSelectedChat: (value?: number) => void; theme: "light" | "dark"; toggleTheme: () => void; locale: Locale; setLocale: (next: Locale) => void; t: (key: any, values?: Record<string, string | number>) => string }): React.JSX.Element {
  const title = t(`nav.${section}` as any);
  return <header className="page-header"><div><p className="eyebrow">{selectedChat ? t("common.chat") : t("common.allChats")}</p><h2>{title}<span className="title-dot">.</span></h2></div><div className="header-actions"><select className="context-select" value={selectedChat ?? "all"} onChange={(event) => setSelectedChat(event.target.value === "all" ? undefined : Number(event.target.value))} aria-label={t("common.chat")}><option value="all">{t("common.allChats")}</option>{chats.map((chat) => <option key={chat.id} value={chat.id}>{chat.title}</option>)}</select><LanguageToggle locale={locale} setLocale={setLocale} label={locale === "ru" ? "Язык" : "Language"} /><button className="icon-button" type="button" aria-label={theme === "light" ? t("theme.dark") : t("theme.light")} onClick={toggleTheme}>{theme === "light" ? "◐" : "○"}</button><button className="avatar" onClick={() => setSelectedChat(undefined)} aria-label={profile.display_name}>{initials(profile.display_name)}</button></div></header>;
}

function MetricCard({ label, value, change, t, locale }: { label: string; value: number; change?: number | null; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element { return <div className="metric-card"><span>{label}</span><strong>{formatNumber(value, locale)}</strong>{change !== undefined && <small className={change == null || change >= 0 ? "up" : "down"}>{change == null ? t("common.new") : delta(change)} <i>{t("common.previous")}</i></small>}</div>; }

function ChatRow({ chat, onOpen, t, locale }: { chat: Chat; onOpen?: () => void; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element { const content = <><span className={`chat-glyph ${chat.is_active ? "live" : "off"}`}>{initials(chat.title)}</span><span className="chat-main"><b>{chat.title || "Untitled chat"}</b><small>{chat.role.toLowerCase()} · {chat.members_count == null ? "—" : formatNumber(chat.members_count, locale)}</small></span><span className="plan-tag">{chat.plan}</span><span className="row-arrow">→</span></>; return onOpen ? <button className="chat-row" type="button" onClick={onOpen} aria-label={`${t("common.openChat")}: ${chat.title}`}>{content}</button> : <div className="chat-row">{content}</div>; }

function Overview({ dashboard, profile, setSection, setSelectedChat, t, locale }: { dashboard: Dashboard; profile: Profile; setSection: (value: Section) => void; setSelectedChat: (value?: number) => void; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element {
  const totals = dashboard.totals;
  return <><section className="hero-strip"><div><p className="eyebrow">{t("overview.context", { count: profile.chats_total })}</p><h1>{t("overview.title")}</h1><p>{t("overview.subtitle")}</p></div><button className="ghost" onClick={() => setSection("activity")}>{t("overview.openActivity")} <span>→</span></button></section><section className="metrics-grid"><MetricCard label={t("common.messages")} value={totals.messages} change={dashboard.deltas_percent.messages} t={t} locale={locale} /><MetricCard label={t("common.activeUsers")} value={totals.active_users} change={dashboard.deltas_percent.active_users} t={t} locale={locale} /><MetricCard label={t("common.joins")} value={totals.joins} change={dashboard.deltas_percent.joins} t={t} locale={locale} /><MetricCard label={t("common.moderation")} value={totals.moderation_actions} change={dashboard.deltas_percent.moderation_actions} t={t} locale={locale} /></section><section className="split"><div className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">{t("overview.signal", { days: dashboard.period_days })}</p><h3>{t("activity.chart")}</h3></div><button className="text-button" onClick={() => setSection("activity")}>{t("overview.fullReport")} →</button></div><Chart series={dashboard.series} metric="messages" total={dashboard.totals.messages} label={t("common.messages")} emptyLabel={t("chart.noData")} locale={locale} /></div><div className="panel focus-panel"><div className="panel-head"><div><p className="eyebrow">{t("overview.focus")}</p><h3>{t("overview.now")}</h3></div></div><div className="focus-row"><span className="focus-number">{formatNumber(dashboard.moderation.total, locale)}</span><span><b>{t("common.moderation")}</b><small>{t("overview.moderationDetail", { automated: dashboard.moderation.automated, mine: dashboard.moderation.mine })}</small></span></div><div className="focus-row"><span className="focus-number">{formatNumber(profile.total_members, locale)}</span><span><b>{t("overview.members")}</b><small>{t("overview.paidPlans", { count: profile.paid_chats })}</small></span></div><button className="outline" onClick={() => setSection("chats")}>{t("overview.reviewChats")} <span>→</span></button></div></section><section className="panel recent-panel"><div className="panel-head"><div><p className="eyebrow">{t("overview.space")}</p><h3>{t("nav.chats")}</h3></div><button className="text-button" onClick={() => setSection("chats")}>{t("overview.seeAll")} →</button></div>{dashboard.chats.slice(0, 3).map((chat) => <ChatRow key={chat.id} chat={chat} onOpen={() => { setSelectedChat(chat.id); setSection("activity"); }} t={t} locale={locale} />)}{dashboard.chats.length === 0 && <Empty text={t("chats.empty")} />}</section></>;
}

function Activity({ dashboard, period, setPeriod, t, locale }: { dashboard: Dashboard; period: Period; setPeriod: (value: Period) => void; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element {
  const [metric, setMetric] = useState<Metric>("messages");
  const labelKey: Record<Metric, any> = { messages: "common.messages", active_users: "common.activeUsers", joins: "common.joins", moderation_actions: "common.moderation" };
  return <><section className="activity-intro"><p className="eyebrow">{t("activity.eyebrow")}</p><h1>{t("activity.title")}</h1><p>{t("activity.subtitle")}</p></section><div className="control-line"><div className="segmented" role="group" aria-label={t("common.period")}>{periods.map((value) => <button key={value} className={period === value ? "selected" : ""} onClick={() => setPeriod(value)}>{value}{t("common.daysShort")}</button>)}</div><div className="metric-tabs" role="group" aria-label={t("common.metric")}>{metrics.map((value) => <button key={value} className={metric === value ? "selected" : ""} onClick={() => setMetric(value)}>{t(labelKey[value])}</button>)}</div></div><section className="panel wide-chart"><Chart series={dashboard.series} metric={metric} total={dashboard.totals[metric]} label={t(labelKey[metric])} emptyLabel={t("chart.noData")} locale={locale} /></section><section className="metrics-grid compact"><MetricCard label={t("common.netGrowth")} value={dashboard.totals.net_growth} change={dashboard.deltas_percent.net_growth} t={t} locale={locale} /><MetricCard label={t("common.joins")} value={dashboard.totals.joins} t={t} locale={locale} /><MetricCard label={t("common.leaves")} value={dashboard.totals.leaves} t={t} locale={locale} /><MetricCard label={t("common.activeUsers")} value={dashboard.totals.active_users} t={t} locale={locale} /></section><section className="split"><div className="panel"><div className="panel-head"><div><p className="eyebrow">{t("common.moderation")}</p><h3>{t("activity.interventions")}</h3></div></div><div className="bars">{dashboard.moderation.breakdown.length ? dashboard.moderation.breakdown.slice(0, 6).map((item) => <div className="bar-row" key={item.action}><span>{item.action.replaceAll("_", " ")}</span><div><i style={{ width: `${Math.min(100, item.count / Math.max(1, dashboard.moderation.total) * 100)}%` }} /></div><b>{item.count}</b></div>) : <Empty text={t("activity.noModeration")} />}</div></div><div className="panel"><div className="panel-head"><div><p className="eyebrow">{t("activity.behaviour")}</p><h3>{t("activity.memberFlow")}</h3></div></div><div className="flow-stat"><b>{formatNumber(dashboard.totals.joins, locale)}</b><span>{t("common.joins")}</span><b>{formatNumber(dashboard.totals.leaves, locale)}</b><span>{t("common.leaves")}</span><strong>{dashboard.totals.net_growth >= 0 ? "+" : ""}{formatNumber(dashboard.totals.net_growth, locale)}</strong><span>{t("common.netGrowth")}</span></div></div></section></>;
}

function Chats({ chats, setSelectedChat, setSection, t, locale }: { chats: Chat[]; setSelectedChat: (value?: number) => void; setSection: (value: Section) => void; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element { return <><section className="activity-intro"><p className="eyebrow">{t("chats.eyebrow")}</p><h1>{t("nav.chats")}</h1><p>{t("chats.subtitle")}</p></section><section className="panel chat-list">{chats.length ? chats.map((chat) => <ChatRow key={chat.id} chat={chat} onOpen={() => { setSelectedChat(chat.id); setSection("activity"); }} t={t} locale={locale} />) : <Empty text={t("chats.empty")} />}</section></>; }

function Plans({ meta, t, locale }: { meta: Meta | null; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element { const [expanded, setExpanded] = useState<string | null>(null); const plans = meta?.plans ?? []; return <><section className="activity-intro"><p className="eyebrow">{t("plans.eyebrow")}</p><h1>{t("nav.plans")}</h1><p>{t("plans.subtitle")}</p></section><section className="plans-grid">{plans.map((plan, index) => { const isExpanded = expanded === plan.plan; const features = isExpanded ? plan.features : plan.features.slice(0, 6); return <article className={`plan-card ${index === 1 ? "featured" : ""}`} key={plan.plan}><div className="plan-index">0{index + 1}</div><h3>{plan.plan}</h3><p className="plan-price">{plan.stars ? `${formatNumber(plan.stars, locale)} Stars` : t("plans.free")}<small>{plan.usd ? ` / ${plan.usd} USD mo` : ` / ${t("plans.forever")}`}</small></p><ul>{features.map((feature) => <li key={feature}>{feature.replaceAll("_", " ")}</li>)}</ul>{plan.features.length > 6 ? <button className="outline" type="button" aria-expanded={isExpanded} onClick={() => setExpanded(isExpanded ? null : plan.plan)}>{isExpanded ? t("plans.showLess") : t("plans.viewAll")} <span>{isExpanded ? "↑" : "↓"}</span></button> : <div className="plan-complete">{t("plans.complete")}</div>}</article>; })}</section></>; }

function ProfileScreen({ profile, t, locale }: { profile: Profile; t: (key: any, values?: Record<string, string | number>) => string; locale: Locale }): React.JSX.Element { return <><section className="profile-hero"><span className="avatar giant">{initials(profile.display_name)}</span><div><p className="eyebrow">TELEGRAM ID / {profile.user.tg_user_id}</p><h1>{profile.display_name}</h1><p>{profile.user.username ? `@${profile.user.username}` : "Telegram"}</p></div></section><section className="metrics-grid compact"><MetricCard label={t("profile.managedChats")} value={profile.chats_total} t={t} locale={locale} /><MetricCard label={t("profile.ownedChats")} value={profile.chats_owned} t={t} locale={locale} /><MetricCard label={t("profile.paidPlans")} value={profile.paid_chats} t={t} locale={locale} /><MetricCard label={t("profile.members")} value={profile.total_members} t={t} locale={locale} /></section><section className="split"><div className="panel detail-list"><div className="panel-head"><div><p className="eyebrow">{t("profile.identity")}</p><h3>{t("profile.details")}</h3></div></div><div><span>{t("profile.firstSeen")}</span><b>{profile.first_seen_at ? formatDate(profile.first_seen_at, locale) : "—"}</b></div><div><span>{t("profile.language")}</span><b>{profile.user.language_code.toUpperCase()}</b></div><div><span>{t("profile.planStatus")}</span><b>{profile.user.is_premium ? "Telegram Premium" : "Standard"}</b></div></div><div className="panel detail-list"><div className="panel-head"><div><p className="eyebrow">{t("profile.access")}</p><h3>{t("profile.security")}</h3></div></div><p className="security-copy">{t("profile.securityCopy")}</p><div className="security-line"><i />{t("profile.encrypted")}</div><div className="security-line"><i />{t("profile.oneTime")}</div></div></section></>; }

function Empty({ text }: { text: string }): React.JSX.Element { return <div className="empty">{text}</div>; }

function DashboardApp({ user, onLogout }: { user: User; onLogout: () => void }): React.JSX.Element {
  const { locale, setLocale, t } = useI18n(user.language_code);
  const [theme, toggleTheme] = useTheme();
  const [section, setSection] = useState<Section>("overview");
  const [period, setPeriod] = useState<Period>(7);
  const [selectedChat, setSelectedChat] = useState<number | undefined>();
  const [profile, setProfile] = useState<Profile | null>(null);
  const [chats, setChats] = useState<Chat[]>([]);
  const [meta, setMeta] = useState<Meta | null>(null);
  const [error, setError] = useState<string | null>(null);
  const dashboardState = useDashboardCache({ userKey: user.tg_user_id, period, chatId: selectedChat });

  useEffect(() => { let current = true; void Promise.all([fetchProfile(), fetchChats(), fetchMeta()]).then(([nextProfile, nextChats, nextMeta]) => { if (!current) return; setProfile(nextProfile); setChats(nextChats); setMeta(nextMeta); setError(null); }).catch((reason: unknown) => { if (!current) return; if (!hasToken()) { onLogout(); return; } setError(reason instanceof Error ? reason.message : ""); }); return () => { current = false; }; }, [onLogout]);
  useEffect(() => { if (dashboardState.error?.message.includes("not connected")) setSelectedChat(undefined); }, [dashboardState.error]);

  if (error !== null && !profile) return <div className="error-page"><p className="eyebrow">{t("common.error")}</p><h1>{t("common.accountUnavailable")}</h1><p>{error || t("common.accountError")}</p><button className="primary" onClick={onLogout}>{t("common.logout")}</button></div>;
  if (!profile || (!dashboardState.data && dashboardState.isLoading)) return <div className="loading-page"><div className="loading-mark"><i /><i /><i /></div><p>{t("common.loading")}</p></div>;
  const dashboard = dashboardState.data;
  if (!dashboard) return <div className="error-page"><p>{dashboardState.error?.message ?? t("common.noData")}</p><button className="primary" onClick={dashboardState.retry}>{t("common.retry")}</button></div>;
  const render = section === "overview" ? <Overview dashboard={dashboard} profile={profile} setSection={setSection} setSelectedChat={setSelectedChat} t={t} locale={locale} /> : section === "activity" ? <Activity dashboard={dashboard} period={period} setPeriod={setPeriod} t={t} locale={locale} /> : section === "chats" ? <Chats chats={chats} setSelectedChat={setSelectedChat} setSection={setSection} t={t} locale={locale} /> : section === "plans" ? <Plans meta={meta} t={t} locale={locale} /> : <ProfileScreen profile={profile} t={t} locale={locale} />;
  const navItems: [Section, TranslationKey][] = [["overview", "nav.overview"], ["activity", "nav.activity"], ["chats", "nav.chats"], ["plans", "nav.plans"], ["profile", "nav.profile"]];
  return <div className="site-shell"><Sidebar section={section} setSection={setSection} profile={profile} theme={theme} toggleTheme={toggleTheme} logout={onLogout} t={t} /><main className="content"><Header section={section} profile={profile} selectedChat={selectedChat} chats={chats} setSelectedChat={setSelectedChat} theme={theme} toggleTheme={toggleTheme} locale={locale} setLocale={setLocale} t={t} />{dashboardState.isRefreshing && <div className="loading-sheen" role="status">{t("common.loading")}</div>}{render}</main><nav className="mobile-nav" aria-label="Primary">{navItems.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}><span>{t(label)}</span></button>)}</nav></div>;
}

export function SiteApp(): React.JSX.Element {
  const [auth, setAuth] = useState<{ user: User } | null>(null);
  const [loginError, setLoginError] = useState<string | null>(null);
  const handleLogout = useCallback(() => { clearToken(); setAuth(null); }, []);
  const finishLogin = (value: string) => { setLoginError(null); void login(value).then((result) => setAuth({ user: result.user })).catch((reason: unknown) => setLoginError(reason instanceof Error ? reason.message : "Invalid key")); };
  useEffect(() => { const match = window.location.hash.match(/token=([^&]+)/); if (!match) return; window.history.replaceState(null, "", window.location.pathname); finishLogin(decodeURIComponent(match[1])); }, []);
  useEffect(() => { if (hasToken() && !auth) void fetchProfile().then((profile) => setAuth({ user: profile.user })).catch(() => clearToken()); }, [auth]);
  if (!auth) return <LoginScreen error={loginError} onLogin={finishLogin} />;
  return <DashboardApp user={auth.user} onLogout={handleLogout} />;
}
