import { useEffect, useMemo, useState } from "react";
import { clearToken, fetchChats, fetchDashboard, fetchMeta, fetchProfile, hasToken, login } from "./api";
import { Chart } from "./components/Chart";
import type { Chat, Dashboard, Meta, Profile, User } from "./types";

type Section = "overview" | "activity" | "chats" | "plans" | "profile";
const periods = [1, 7, 30, 90] as const;

function useTheme(): ["light" | "dark", () => void] {
  const [theme, setTheme] = useState<"light" | "dark">(() => (localStorage.getItem("tg-manager-theme") as "light" | "dark") || "light");
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("tg-manager-theme", theme); }, [theme]);
  return [theme, () => setTheme((value) => value === "light" ? "dark" : "light")];
}

function initials(name: string): string { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "TG"; }
function formatDate(value: string | null): string { return value ? new Date(value).toLocaleDateString(undefined, { dateStyle: "medium" }) : "Not available"; }
function delta(value: number | null | undefined): string { return value == null ? "New" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }

function LoginScreen({ error, onLogin }: { error: string | null; onLogin: (value: string) => void }): React.JSX.Element {
  const [value, setValue] = useState("");
  return <main className="login-page"><div className="login-mark" aria-hidden="true"><i /><i /><i /></div><p className="eyebrow">TELEGRAM MANAGER / ACCOUNT</p><h1>Your chats,<br /><em>in focus.</em></h1><p className="login-copy">A private view of activity, moderation and plans across every chat you manage.</p><form onSubmit={(event) => { event.preventDefault(); if (value.trim()) onLogin(value.trim()); }}><label>One-time access key<input autoFocus value={value} onChange={(event) => setValue(event.target.value)} placeholder="Paste the key from /website" /></label><button className="primary" type="submit" disabled={!value.trim()}>Open dashboard <span>↗</span></button></form>{error && <p className="form-error" role="alert">{error}</p>}<p className="login-note">Keys are single-use, expire quickly and are never stored in the browser URL after sign-in.</p></main>;
}

function Sidebar({ section, setSection, profile, theme, toggleTheme, logout }: { section: Section; setSection: (value: Section) => void; profile: Profile; theme: string; toggleTheme: () => void; logout: () => void }): React.JSX.Element {
  const items: [Section, string, string][] = [["overview", "Overview", "01"], ["activity", "Activity", "02"], ["chats", "My chats", "03"], ["plans", "Plans", "04"], ["profile", "Profile", "05"]];
  return <aside className="sidebar"><div className="brand"><span className="brand-mark"><i /><i /><i /></span><span>tg / manager</span></div><nav>{items.map(([key, label, number]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}><small>{number}</small>{label}</button>)}</nav><div className="side-bottom"><button className="theme-button" onClick={toggleTheme}><span>{theme === "light" ? "◐" : "○"}</span>{theme === "light" ? "Dark mode" : "Light mode"}</button><button className="account-mini" onClick={() => setSection("profile")}><span className="avatar small">{initials(profile.display_name)}</span><span><b>{profile.display_name}</b><small>{profile.user.username ? `@${profile.user.username}` : "Telegram account"}</small></span><span>↗</span></button><button className="logout" onClick={logout}>Sign out</button></div></aside>;
}

function Header({ section, profile, setSection, theme, toggleTheme }: { section: Section; profile: Profile; setSection: (v: Section) => void; theme: "light" | "dark"; toggleTheme: () => void }): React.JSX.Element {
  const title = section === "overview" ? "Good to see you" : section === "activity" ? "Activity" : section === "chats" ? "My chats" : section === "plans" ? "Plans" : "Profile";
  return <header className="page-header"><div><p className="eyebrow">{section === "overview" ? "ACCOUNT OVERVIEW" : `ACCOUNT / ${section.toUpperCase()}`}</p><h2>{title}{section === "overview" && <span className="title-dot">.</span>}</h2></div><div className="header-actions"><span className="status"><i /> Connected</span><button className="theme-compact" type="button" aria-label={theme === "light" ? "Use dark theme" : "Use light theme"} title={theme === "light" ? "Dark theme" : "Light theme"} onClick={toggleTheme}>{theme === "light" ? "◐" : "○"}</button><button className="avatar" onClick={() => setSection("profile")}>{initials(profile.display_name)}</button></div></header>;
}

function MetricCard({ label, value, change }: { label: string; value: number; change?: number | null }): React.JSX.Element { return <div className="metric-card"><span>{label}</span><strong>{value.toLocaleString()}</strong>{change !== undefined && <small className={change == null || change >= 0 ? "up" : "down"}>{delta(change)} <i>vs previous</i></small>}</div>; }

function Overview({ dashboard, profile, setSection, setPeriod }: { dashboard: Dashboard; profile: Profile; setSection: (v: Section) => void; setPeriod: (v: typeof periods[number]) => void }): React.JSX.Element {
  const totals = dashboard.totals;
  return <><section className="hero-strip"><div><p className="eyebrow">{profile.chats_total} MANAGED {profile.chats_total === 1 ? "CHAT" : "CHATS"}</p><h1>Quiet control.<br /><em>Clear signal.</em></h1><p>Everything your moderation work has done, in one composed view.</p></div><button className="ghost" onClick={() => setSection("activity")}>Explore activity <span>→</span></button></section><section className="metrics-grid"><MetricCard label="Messages" value={totals.messages} change={dashboard.deltas_percent.messages} /><MetricCard label="Active users" value={totals.active_users} change={dashboard.deltas_percent.active_users} /><MetricCard label="New joins" value={totals.joins} change={dashboard.deltas_percent.joins} /><MetricCard label="Moderation actions" value={totals.moderation_actions} change={dashboard.deltas_percent.moderation_actions} /></section><section className="split"><div className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">SIGNAL / {dashboard.period_days} DAYS</p><h3>Message flow</h3></div><button className="text-button" onClick={() => setSection("activity")}>Full report →</button></div><Chart series={dashboard.series} metric="messages" /></div><div className="panel focus-panel"><div className="panel-head"><div><p className="eyebrow">FOCUS</p><h3>What matters now</h3></div></div><div className="focus-row"><span className="focus-number">{dashboard.moderation.total}</span><span><b>moderation actions</b><small>{dashboard.moderation.automated} automated · {dashboard.moderation.mine} by you</small></span></div><div className="focus-row"><span className="focus-number">{profile.total_members.toLocaleString()}</span><span><b>members across chats</b><small>{profile.paid_chats} paid {profile.paid_chats === 1 ? "plan" : "plans"}</small></span></div><button className="outline" onClick={() => setSection("chats")}>Review managed chats <span>→</span></button></div></section><section className="panel recent-panel"><div className="panel-head"><div><p className="eyebrow">YOUR SPACE</p><h3>Managed chats</h3></div><button className="text-button" onClick={() => setSection("chats")}>See all →</button></div>{dashboard.chats.slice(0, 3).map((chat) => <ChatRow key={chat.id} chat={chat} />)}{dashboard.chats.length === 0 && <Empty text="No connected chats yet. Add the bot as an administrator to begin." />}</section><div className="period-hint">Current view is <button onClick={() => setPeriod(7)}>7 days</button>. Change the range in Activity.</div></>;
}

function ChatRow({ chat }: { chat: Chat }): React.JSX.Element { return <div className="chat-row"><span className={`chat-glyph ${chat.is_active ? "live" : "off"}`}>{initials(chat.title)}</span><span className="chat-main"><b>{chat.title || "Untitled chat"}</b><small>{chat.role.toLowerCase()} · {chat.members_count?.toLocaleString() ?? "—"} members</small></span><span className="plan-tag">{chat.plan}</span><span className="row-arrow">→</span></div>; }
function Empty({ text }: { text: string }): React.JSX.Element { return <div className="empty">{text}</div>; }

function Activity({ dashboard, period, setPeriod }: { dashboard: Dashboard; period: typeof periods[number]; setPeriod: (v: typeof periods[number]) => void }): React.JSX.Element {
  const [metric, setMetric] = useState<"messages" | "active_users" | "joins" | "moderation_actions">("messages");
  return <><section className="activity-intro"><p className="eyebrow">MEASURED ACTIVITY</p><h1>Read the room.</h1><p>Compare movement across your managed chats without losing the shape of the story.</p></section><div className="control-line"><div className="segmented">{periods.map((value) => <button key={value} className={period === value ? "selected" : ""} onClick={() => setPeriod(value)}>{value}d</button>)}</div><div className="metric-tabs">{(["messages", "active_users", "joins", "moderation_actions"] as const).map((value) => <button key={value} className={metric === value ? "selected" : ""} onClick={() => setMetric(value)}>{value === "active_users" ? "Users" : value === "moderation_actions" ? "Moderation" : value[0].toUpperCase() + value.slice(1)}</button>)}</div></div><section className="panel wide-chart chart-transition" key={`${period}-${metric}`}><Chart series={dashboard.series} metric={metric} /></section><section className="metrics-grid compact"><MetricCard label="Net growth" value={dashboard.totals.net_growth} change={dashboard.deltas_percent.net_growth} /><MetricCard label="Joins" value={dashboard.totals.joins} /><MetricCard label="Leaves" value={dashboard.totals.leaves} /><MetricCard label="Active users" value={dashboard.totals.active_users} /></section><section className="split"><div className="panel"><div className="panel-head"><div><p className="eyebrow">MODERATION</p><h3>Interventions</h3></div></div><div className="bars">{dashboard.moderation.breakdown.length ? dashboard.moderation.breakdown.slice(0, 6).map((item) => <div className="bar-row" key={item.action}><span>{item.action.replaceAll("_", " ")}</span><div><i style={{ width: `${Math.min(100, item.count / Math.max(1, dashboard.moderation.total) * 100)}%` }} /></div><b>{item.count}</b></div>) : <Empty text="No moderation actions in this period." />}</div></div><div className="panel"><div className="panel-head"><div><p className="eyebrow">BEHAVIOUR</p><h3>Member flow</h3></div></div><div className="flow-stat"><b>{dashboard.totals.joins}</b><span>joined</span><b>{dashboard.totals.leaves}</b><span>left</span><strong>{dashboard.totals.net_growth >= 0 ? "+" : ""}{dashboard.totals.net_growth}</strong><span>net</span></div></div></section></>;
}

function Chats({ chats }: { chats: Chat[] }): React.JSX.Element { return <><section className="activity-intro"><p className="eyebrow">CONNECTED SURFACES</p><h1>Your chats.</h1><p>Every room you manage, its current plan and the people behind the numbers.</p></section><section className="panel chat-list">{chats.length ? chats.map((chat) => <ChatRow key={chat.id} chat={chat} />) : <Empty text="No connected chats yet." />}</section></>; }
function Plans({ meta }: { meta: Meta | null }): React.JSX.Element { const plans = meta?.plans ?? []; const [expanded, setExpanded] = useState<string | null>(null); return <><section className="activity-intro"><p className="eyebrow">CAPABILITY MAP</p><h1>Choose your pace.</h1><p>Plans are attached to a chat, so every team gets exactly the room it needs.</p></section><section className="plans-grid">{plans.map((plan, index) => { const isExpanded = expanded === plan.plan; const features = isExpanded ? plan.features : plan.features.slice(0, 6); return <article className={`plan-card ${index === 1 ? "featured" : ""}`} key={plan.plan}><div className="plan-index">0{index + 1}</div><h3>{plan.plan}</h3><p className="plan-price">{plan.stars ? `${plan.stars} Stars` : "Free"}<small>{plan.usd ? ` / ${plan.usd} USD mo` : " / forever"}</small></p><ul>{features.map((feature) => <li key={feature}>{feature.replaceAll("_", " ")}</li>)}</ul>{plan.features.length > 6 ? <button className="outline" type="button" aria-expanded={isExpanded} onClick={() => setExpanded(isExpanded ? null : plan.plan)}>{isExpanded ? "Show less" : "View all capabilities"} <span>{isExpanded ? "↑" : "↓"}</span></button> : <div className="plan-complete">Complete capability list</div>}</article>; })}</section></>; }
function Profile({ profile }: { profile: Profile }): React.JSX.Element { return <><section className="profile-hero"><span className="avatar giant">{initials(profile.display_name)}</span><div><p className="eyebrow">TELEGRAM ID / {profile.user.tg_user_id}</p><h1>{profile.display_name}</h1><p>{profile.user.username ? `@${profile.user.username}` : "Telegram account"}</p></div></section><section className="metrics-grid compact"><MetricCard label="Managed chats" value={profile.chats_total} /><MetricCard label="Owned chats" value={profile.chats_owned} /><MetricCard label="Paid plans" value={profile.paid_chats} /><MetricCard label="Known members" value={profile.total_members} /></section><section className="split"><div className="panel detail-list"><div className="panel-head"><div><p className="eyebrow">IDENTITY</p><h3>Account details</h3></div></div><div><span>First seen</span><b>{formatDate(profile.first_seen_at)}</b></div><div><span>Language</span><b>{profile.user.language_code.toUpperCase()}</b></div><div><span>Plan status</span><b>{profile.user.is_premium ? "Telegram Premium" : "Standard account"}</b></div></div><div className="panel detail-list"><div className="panel-head"><div><p className="eyebrow">ACCESS</p><h3>Security note</h3></div></div><p className="security-copy">This website uses a short-lived key issued by the bot. Your Telegram ID is resolved on the server; the browser never chooses which account data to load.</p><div className="security-line"><i /> Session encrypted in transit</div><div className="security-line"><i /> One-time key invalidated</div></div></section></>; }

function DashboardApp({ user, onLogout }: { user: User; onLogout: () => void }): React.JSX.Element {
  const [theme, toggleTheme] = useTheme(); const [section, setSection] = useState<Section>("overview"); const [period, setPeriod] = useState<typeof periods[number]>(7); const [profile, setProfile] = useState<Profile | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [chats, setChats] = useState<Chat[]>([]); const [meta, setMeta] = useState<Meta | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let current = true; void Promise.all([fetchProfile(), fetchDashboard(period), fetchChats(), fetchMeta()]).then(([nextProfile, nextDashboard, nextChats, nextMeta]) => { if (!current) return; setProfile(nextProfile); setDashboard(nextDashboard); setChats(nextChats); setMeta(nextMeta); setError(null); }).catch((reason: unknown) => { if (!current) return; if (!hasToken()) { onLogout(); return; } setError(reason instanceof Error ? reason.message : "Could not load account"); }); return () => { current = false; }; }, [period]);
  useEffect(() => { if (user) document.title = `${user.first_name || "Account"} / Telegram Manager`; }, [user]);
  if (error && !profile) return <div className="error-page"><p className="eyebrow">ACCOUNT UNAVAILABLE</p><h1>Something went quiet.</h1><p>{error}</p><button className="primary" onClick={onLogout}>Return to sign in</button></div>;
  if (!profile || !dashboard) return <div className="loading-page"><div className="loading-mark"><i /><i /><i /></div><p>Preparing your account</p></div>;
  return <div className="site-shell"><Sidebar section={section} setSection={setSection} profile={profile} theme={theme} toggleTheme={toggleTheme} logout={onLogout} /><main className="content"><Header section={section} profile={profile} setSection={setSection} theme={theme} toggleTheme={toggleTheme} />{section === "overview" && <Overview dashboard={dashboard} profile={profile} setSection={setSection} setPeriod={setPeriod} />}{section === "activity" && <Activity dashboard={dashboard} period={period} setPeriod={setPeriod} />}{section === "chats" && <Chats chats={chats} />}{section === "plans" && <Plans meta={meta} />}{section === "profile" && <Profile profile={profile} />}</main><div className="mobile-nav">{([["overview", "Overview"], ["activity", "Activity"], ["chats", "Chats"], ["plans", "Plans"], ["profile", "Profile"]] as [Section, string][]).map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}><span>{key === "overview" ? "01" : key === "activity" ? "02" : key === "chats" ? "03" : key === "plans" ? "04" : "05"}</span>{label}</button>)}</div></div>;
}

export function SiteApp(): React.JSX.Element {
  const [auth, setAuth] = useState<{ user: User } | null>(null); const [loginError, setLoginError] = useState<string | null>(null);
  useEffect(() => { const hash = window.location.hash; const match = hash.match(/token=([^&]+)/); if (match) { const raw = decodeURIComponent(match[1]); window.history.replaceState(null, "", window.location.pathname); void login(raw).then((result) => setAuth({ user: result.user })).catch((reason: unknown) => setLoginError(reason instanceof Error ? reason.message : "The key is invalid or expired")); } }, []);
  useEffect(() => { if (hasToken() && !auth) void fetchProfile().then((profile) => setAuth({ user: profile.user })).catch(() => clearToken()); }, [auth]);
  if (!auth) return <LoginScreen error={loginError} onLogin={(value) => { setLoginError(null); void login(value).then((result) => setAuth({ user: result.user })).catch((reason: unknown) => setLoginError(reason instanceof Error ? reason.message : "The key is invalid or expired")); }} />;
  return <DashboardApp user={auth.user} onLogout={() => { clearToken(); setAuth(null); }} />;
}
