/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always 200 while the process is up — no dependency is consulted.
         *
         *     A liveness probe that fails when Redis is down would have the orchestrator
         *     restart a perfectly healthy API, which does not bring Redis back.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description 503 while a dependency the API cannot serve without is unreachable.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Module catalog, plan matrix and shipped locales */
        get: operations["getPlatformMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Telegram initData for an API session token */
        post: operations["authenticateWithTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew a session token that has not expired yet */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller behind the current session token */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chats where the caller is an administrator */
        get: operations["listChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One chat with its module state and unlocked features */
        get: operations["getChat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update chat-level settings (language, timezone) */
        patch: operations["updateChat"];
        trace?: never;
    };
    "/api/chats/{chat_id}/admins/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-read the chat's administrator list from Telegram
         * @description Refresh the mirror the chat list is drawn from, and drop cached verdicts.
         *
         *     Telegram sends no update on a promotion, so this is how a newly promoted
         *     admin makes the chat appear in their panel without waiting for the bot to
         *     happen to sync it.
         */
        post: operations["syncChatAdmins"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The plan actually in force for a chat */
        get: operations["getChatPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every module's settings for one chat
         * @description One payload for the whole settings screen — locked modules included.
         *
         *     Locked modules are returned rather than hidden: the panel renders them
         *     greyed out with the plan that unlocks them, which is the paywall.
         */
        get: operations["listModuleConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/modules/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One module's settings */
        get: operations["getModuleConfig"];
        /** Replace a module's settings wholesale */
        put: operations["replaceModuleConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Merge a partial settings update into a module */
        patch: operations["patchModuleConfig"];
        trace?: never;
    };
    "/api/chats/{chat_id}/modules/{module}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a module's default settings */
        post: operations["resetModuleConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminRole
         * @enum {string}
         */
        AdminRole: "owner" | "admin";
        /**
         * AuthRequest
         * @description Raw `initData` string handed over by the Telegram WebApp SDK.
         */
        AuthRequest: {
            /** Init Data */
            init_data: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["AuthUser"];
        };
        /** AuthUser */
        AuthUser: {
            /** Tg User Id */
            tg_user_id: number;
            /** Username */
            username?: string | null;
            /**
             * First Name
             * @default
             */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /**
             * Language Code
             * @default en
             */
            language_code: string;
            /**
             * Is Superadmin
             * @default false
             */
            is_superadmin: boolean;
        };
        /** ChatDetail */
        ChatDetail: {
            /** Id */
            id: number;
            /** Tg Chat Id */
            tg_chat_id: number;
            /** Title */
            title: string;
            type: components["schemas"]["ChatType"];
            plan: components["schemas"]["Plan"];
            /** Plan Expires At */
            plan_expires_at?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** @default admin */
            role: components["schemas"]["AdminRole"];
            /** Members Count */
            members_count?: number | null;
            /** Owner Tg Id */
            owner_tg_id?: number | null;
            /**
             * Language
             * @default ru
             */
            language: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Modules */
            modules?: {
                [key: string]: boolean;
            };
            /** Features */
            features?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /** ChatSummary */
        ChatSummary: {
            /** Id */
            id: number;
            /** Tg Chat Id */
            tg_chat_id: number;
            /** Title */
            title: string;
            type: components["schemas"]["ChatType"];
            plan: components["schemas"]["Plan"];
            /** Plan Expires At */
            plan_expires_at?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** @default admin */
            role: components["schemas"]["AdminRole"];
            /** Members Count */
            members_count?: number | null;
        };
        /**
         * ChatType
         * @enum {string}
         */
        ChatType: "group" | "supergroup" | "channel";
        /** ChatUpdate */
        ChatUpdate: {
            /** Language */
            language?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** CommandMeta */
        CommandMeta: {
            /** Name */
            name: string;
            /** Description Key */
            description_key: string;
            /**
             * Admin Only
             * @default true
             */
            admin_only: boolean;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Modules */
            modules?: components["schemas"]["ModuleMeta"][];
            /** Plans */
            plans?: components["schemas"]["PlanMeta"][];
            /** Locales */
            locales?: string[];
        };
        /** ModuleConfigResponse */
        ModuleConfigResponse: {
            /** Module */
            module: string;
            /** Enabled */
            enabled: boolean;
            required_plan: components["schemas"]["Plan"];
            /** Available */
            available: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** ModuleConfigUpdate */
        ModuleConfigUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ModuleMeta
         * @description One module as the Mini App needs to draw it, before any chat is chosen.
         */
        ModuleMeta: {
            /** Name */
            name: string;
            /** Title Key */
            title_key: string;
            /** Description Key */
            description_key: string;
            required_plan: components["schemas"]["Plan"];
            /**
             * Mandatory
             * @default false
             */
            mandatory: boolean;
            /**
             * Enabled By Default
             * @default false
             */
            enabled_by_default: boolean;
            /** Section Key */
            section_key?: string | null;
            /**
             * Icon
             * @default settings
             */
            icon: string;
            /**
             * Order
             * @default 100
             */
            order: number;
            /** Commands */
            commands?: components["schemas"]["CommandMeta"][];
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            };
        };
        /** OperationResult */
        OperationResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * Plan
         * @enum {string}
         */
        Plan: "free" | "pro" | "business" | "white_label";
        /** PlanMeta */
        PlanMeta: {
            plan: components["schemas"]["Plan"];
            /**
             * Stars
             * @default 0
             */
            stars: number;
            /**
             * Usd
             * @default
             */
            usd: string;
            /** Features */
            features?: string[];
            /** Limits */
            limits?: {
                [key: string]: number;
            };
        };
        /**
         * Problem
         * @description RFC7807-like error body returned by the API exception handler.
         *
         *     `title` is localized for the caller and safe to show; `detail` is the
         *     developer-facing message. `code` is the stable machine-readable discriminator
         *     the Mini App branches on, and `context` carries whatever the error knew (the
         *     required plan for a paywall, the offending field for a validation failure).
         */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Instance */
            instance?: string | null;
            /**
             * Code
             * @default domain-error
             */
            code: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getPlatformMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    authenticateWithTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"][];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    syncChatAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getChatPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listModuleConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfigResponse"][];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The chat's plan does not include this feature. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getModuleConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfigResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The chat's plan does not include this feature. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    replaceModuleConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfigResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The chat's plan does not include this feature. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    patchModuleConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfigResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The chat's plan does not include this feature. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resetModuleConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfigResponse"];
                };
            };
            /** @description Session token missing, malformed or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The chat's plan does not include this feature. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such chat, or the caller does not administer it. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
